version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chart.js
    versions:
    - 2.9.4
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: slug
    versions:
    - 4.0.2
    - 4.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: dot-prop
    versions:
    - 5.2.0
